# Kubernetes configuration
kubernetes:
  # kubeconfig: /Users/rodgon/code/kubernetes-sandbox-credentials/sandbox.aws.kindredgroup.com/kubeconfig
  kubeconfig: /Users/rodgon/code/kubernetes-configuration/k8s.amo.sre.kindredgroup.com/cluster-config/readonly_user.conf
  context: "k8s.sandbox.kindredgroup.com"
  namespace: ""
  resources:
    # - pods
    # - deployments
    # - services
    - nodes

# Storage configuration
storage:
  type: qdrant
  storeAlerts: false
  qdrant:
    url: http://localhost:6333
    collection: alerts
    vectorSize: 384
    distanceMetric: cosine
  redis:
    address: localhost:6379
    password: ""
    db: 0
    keyPrefix: "valkyrie:"

# Notification configuration
notification:
  enabled: true
  type: alertmanager
  minSeverity: warning
  slack:
    webhookUrl: ""
    channel: "#alerts"
    username: "Valkyrie"
  email:
    smtpHost: ""
    smtpPort: 587
    username: ""
    password: ""
    from: ""
    to: []
  webhook:
    url: ""
    method: POST
    headers: {}
  alertmanager:
    url: http://localhost:9093/api/v2/alerts
    labels:
      app: valkyrie
      severity: warning

# Agent configuration
agent:
  learningRate: 0.1
  observationInterval: 30s
  maxHistorySize: 1000
  thresholds:
    cpu: 80.0
    memory: 80.0
    podRestarts: 3



# EWMA alpha tuning guidelines:
#   - alpha controls how much weight is given to the most recent value in EWMA.
#   - alpha close to 1: EWMA reacts quickly to recent changes (less smoothing, more sensitive).
#   - alpha close to 0: EWMA reacts slowly, smoothing out short-term fluctuations (more smoothing, less sensitive).
#   - For noisy data, use a lower alpha (e.g., 0.1–0.3) to smooth out spikes.
#   - For rapid change detection, use a higher alpha (e.g., 0.5–0.8).
#   - Typical values: 0.2–0.4 for most monitoring scenarios.
#   - Try different values and plot the results to see what works best for your use case.

# Anomaly detection configuration
anomalyDetection:
  cpuThreshold: 80.0
  memoryThreshold: 80.0
  podRestartThreshold: 3
  maxHistorySize: 1000
  cpuAlpha: 0.015
  memoryAlpha: 0.015
  restartAlpha: 0.015
  minStdDev: 10.0  # Minimum standard deviation required for statistical analysis

# Embedding configuration
embedding:
  type: simple
  dimension: 384
  openai:
    apiKey: ""
    model: text-embedding-ada-002
  sentenceTransformers:
    model: all-MiniLM-L6-v2
    device: cpu
  ollama:
    url: http://localhost:11434
    model: nomic-embed-text
