global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "valkyrie_alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Valkyrie anomaly detection metrics
  - job_name: 'valkyrie'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Use host.docker.internal to access localhost from container
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true

  # Optional: Add more targets if you have other services
  # - job_name: 'kubernetes'
  #   static_configs:
  #     - targets: ['kubernetes.default.svc:8080'] 